###########################################################
### Welcome to Beautiful Jekyll!
### This config file contains settings for your entire website. 
### Adjust these settings during initial setup, and later changes will likely be minimal.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: Zhihao Zhou's Portfolio

# Your name to show in the footer
author: Zhihao Zhou

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Education: "education"
  Experience: "experience"
  Honors & Awards: "honors"
  Contact: "contact"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

# Add your contact information in the footer.
social-network-links:
  email: "zhihao.zhou@student.kuleuven.be"
  github: jihochau
  linkedin: "https://www.linkedin.com/in/zhihao-zhou"

# RSS feed description
rss-description: "Welcome to my portfolio, a space to showcase my academic and professional achievements."

###########################
# --- General options --- #
###########################

# Social sharing links for posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# Footer link
url-pretty: "jihochau.com"

# Add the website title to every page's title
title-on-all-pages: true

# Excerpt length for blog posts
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

# Enable search button in the navbar
post_search: true

# Display options for sub-menus
navbar-var-length: false

# SEO keywords
#keywords: "Computer Architecture, Electrical Engineering, Embedded Systems, Data Analysis, Programming"

######################################
# --- Colors / Background Image --- #
######################################

# Customize website colors
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Optional background images for navbar, footer, and page
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Mobile theme color suggestion
#mobile-theme-col: "#0085A1"

#################################
# --- Web Analytics Section --- #
#################################

# Google Analytics tag ID
#gtag: "G-XXXXXXXXXX"

####################
# --- Comments --- #
####################

# Disqus comments
#disqus: ""

# Facebook Comments
#fb_comment_id: ""

################
# --- Misc --- #
################

# Date format for posts
date_format: "%B %-d, %Y"

# Timezone
timezone: "Europe/Brussels"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude these files from the production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
